'use client'
import { useContext } from 'react'
import LocaleProvider, { LocaleContext } from '../context/Locale'
import { Layout } from '../types/next'
import './globals.css'

export const metadata = {
  title: 'Antonio Colagreco',
  description: 'Generated by create next app',
}

const RootLayout: Layout = async (props) => {
  const { children } = props
  const locale = useContext(LocaleContext).locale

  return (
    <LocaleProvider>
      <html lang={locale.language}>
        <body className=''>{children}</body>
      </html>
    </LocaleProvider>
  )
}

export default RootLayout

